
NORMALIZATION_MAP = {
    # Soccer

    "he scores!": "goal",
    "goal!": "goal",
    "and it's in!": "goal",
    "what a goal!": "goal",
    "brilliant finish!": "goal",
    "he finds the net": "goal",
    "he buries it in the net": "goal",
    "incredible strike!": "goal",
    "that's sensational!": "goal",
    "a fantastic finish": "goal",
    "it's a beauty!": "goal",
    "unstoppable!": "goal",

    # Powerful Goals
    "a thunderous strike!": "goal",
    "what a rocket!": "goal",
    "he smashes it home!": "goal",
    "unstoppable shot!": "goal",
    "he blasts it into the net": "goal",
    "a bullet of a shot!": "goal",
    "he hammers it in!": "goal",
    "a powerful drive": "goal",
    "top corner finish!": "goal",
    "roof of the net!": "goal",

    # Precise and Skillful Goals
    "a perfectly placed shot": "goal",
    "he slots it past the keeper": "goal",
    "a cool finish": "goal",
    "a clinical strike": "goal",
    "he dinks it over the keeper": "goal",
    "a delightful chip": "goal",
    "a cheeky lob": "goal",
    "he picks his spot": "goal",
    "a composed finish": "goal",
    "ice-cold finish!": "goal",
    "he tucks it away!": "goal",

    # Headers and Set Piece Goals
    "a towering header": "header_goal",
    "bullet header into the net": "header_goal",
    "a glancing header": "header_goal",
    "he heads it home!": "header_goal",
    "unstoppable header!": "header_goal",
    "direct free kick goal!": "free_kick_goal",
    "he bends it like Beckham!": "free_kick_goal",
    "a curling free kick!": "free_kick_goal",
    "he drills the free kick": "free_kick_goal",
    "straight from the corner!": "corner_goal",
    "he volleys it in from the corner": "corner_goal",
    "a bicycle kick from the corner": "corner_goal",

    # Long-Range Goals
    "a screamer from distance!": "goal",
    "a wonder strike!": "goal",
    "he scores from 30 yards out!": "long_range_goal",
    "an unbelievable long shot!": "long_range_goal",
    "a goal out of nowhere!": "long_range_goal",
    "he fires it from outside the box!": "long_range_goal",
    "what a hit from range!": "long_range_goal",
    "a thunderbolt from 25 yards!": "long_range_goal",
    "goalkeeper caught off his line": "long_range_goal",
    "from the halfway line!": "long_range_goal",

    # Deflected Goals
    "he gets a lucky deflection": "deflected_goal",
    "off the defender and in!": "deflected_goal",
    "a wicked deflection!": "deflected_goal",
    "it takes a huge deflection": "deflected_goal",
    "keeper wrong-footed by the deflection": "deflected_goal",
    "a fortunate goal": "deflected_goal",

    # Dramatic and Emotional Goals
    "a last-minute winner!": "last_minute_goal",
    "he wins it at the death!": "last_minute_goal",
    "stoppage time drama!": "last_minute_goal",
    "heartbreak for the opposition!": "last_minute_goal",
    "he saves the day!": "last_minute_goal",
    "an injury-time equalizer": "last_minute_goal",
    "an unforgettable moment!": "goal",
    "pandemonium in the stands!": "goal",

    # Unique and Rare Goals
    "a backheel into the net!": "backheel_goal",
    "a scorpion kick goal!": "scorpion_kick_goal",
    "an overhead kick!": "bicycle_kick_goal",
    "a bicycle kick goal!": "bicycle_kick_goal",
    "a rabona finish!": "rabona_goal",
    "a nutmeg and a goal!": "nutmeg_goal",
    "straight from the kickoff!": "kickoff_goal",
    "an own goal turned into their net": "own_goal",
    "a volley into the net!": "volley_goal",
    "a thunderous half-volley!": "volley_goal",

    # Teamwork Goals
    "what a team goal!": "team_goal",
    "an incredible passing move": "team_goal",
    "he finishes a beautiful build-up": "team_goal",
    "a one-two and a goal!": "team_goal",
    "he taps it in after a great assist": "team_goal",
    "what an unselfish pass!": "team_goal",
    "a simple tap-in": "tap_in_goal",
    "a cutback and a goal!": "team_goal",

    # Fan Reactions
    "the crowd erupts!": "goal",
    "pandemonium in the stadium!": "goal",
    "roars from the fans!": "goal",
    "what a moment for the fans!": "goal",
    "the stands are going crazy!": "goal",
    "he shoots and scores": "goal",
    "goal!": "goal",
    "what a goal": "goal",
    "that's brilliant": "goal",
    "into the back of the net": "goal",
    "goal for the home team": "goal",
    "and it's in": "goal",
    "he finds the net": "goal",
    "a fantastic finish": "goal",
    "world-class strike": "goal",
    "he buries it": "goal",
    "header goal!": "header_goal",
    "deflected into the goal": "goal",
    "unbelievable goal": "goal",
    "it's a hat-trick": "hat_trick",
    "hat-trick hero": "hat_trick",
    "own goal by the defender": "own_goal",
    "last-minute winner": "last_minute_goal",
    
    # Near-Miss and Attempted Goals
    "off the crossbar": "miss",
    "off the woodwork": "miss",
    "just wide of the post": "miss",
    "saved by the keeper": "save",
    "what a miss": "miss",
    "narrowly misses the target": "miss",
    "he should have scored there": "miss",
    "cleared off the line": "goal_line_clearance",

    # Penalties and Fouls
    "it's a penalty": "penalty",
    "penalty awarded": "penalty",
    "handball in the box": "penalty",
    "foul in the penalty area": "penalty",
    "dangerous play": "foul",
    "yellow card shown": "yellow_card",
    "he's been booked": "yellow_card",
    "red card shown": "red_card",
    "sent off for a foul": "red_card",
    "that's a reckless challenge": "foul",
    "offside flag is up": "offside",
    "he's offside": "offside",
    "clear offside decision": "offside",
    "free kick given": "free_kick",
    "it's a free kick": "free_kick",
    
    # Saves and Defensive Plays
    "great save by the keeper": "save",
    "brilliant goalkeeping": "save",
    "he parries it away": "save",
    "incredible stop": "save",
    "blocked by the defender": "block",
    "last-ditch tackle": "last_ditch_tackle",
    "goalkeeper punches it clear": "punch_clearance",
    "he clears it off the line": "goal_line_clearance",
    "deflected out for a corner": "deflection",
    "an excellent interception": "interception",

    # Set Pieces and Corners
    "corner kick": "corner",
    "corner delivered": "corner",
    "short corner taken": "short_corner",
    "free kick in a dangerous position": "free_kick",
    "a quick free kick": "quick_free_kick",
    "long throw into the box": "throw_in",
    "throw-in taken": "throw_in",
    "direct free kick on target": "direct_free_kick",
    "curled into the box": "cross",

    # Match Events
    "kick-off": "kick_off",
    "full-time whistle": "full_time_whistle",
    "half-time whistle": "half_time_whistle",
    "injury time added": "injury_time",
    "substitution made": "substitution",
    "double substitution": "substitution",
    "man of the match announced": "man_of_the_match",
    "extra time begins": "extra_time",
    "final whistle": "final_whistle",
    "draw at full-time": "draw",
    "players take a water break": "water_break",
    "the referee consults VAR": "var_check",
    "goal confirmed after VAR review": "var_goal",
    "offside call overturned by VAR": "var_offside",

    # Attacking Play
    "brilliant through ball": "through_ball",
    "what a dribble": "dribble",
    "he skips past the defender": "dribble",
    "long ball forward": "long_ball",
    "cross into the box": "cross",
    "low cross delivered": "low_cross",
    "he chips it forward": "chipped_pass",
    "beautiful link-up play": "link_up",
    "one-two pass completed": "one_two",
    "cutback into the area": "cutback",
    "he takes on the defender": "1v1",

    # Crowd and Reactions
    "the crowd goes wild": "crowd_cheer",
    "chants from the away end": "crowd_chant",
    "boos ring around the stadium": "crowd_boo",
    "jeers from the crowd": "crowd_jeer",
    "the home fans are ecstatic": "crowd_cheer",
    "celebrations on the bench": "bench_celebration",
    "the manager is furious": "manager_fury",
    "loud applause from the stands": "crowd_applause",
    "chants of support": "crowd_chant",
    
    # Miscellaneous
    "rain pouring down on the pitch": "rain",
    "it's a windy day at the stadium": "wind",
    "pitch invader being removed": "pitch_invader",
    "he's receiving treatment": "injury",
    "players stop for a drinks break": "water_break",
    "the referee has blown for VAR": "var_check",
    # Football (American)
    "touchdown pass": "touchdown",
    "he runs it into the end zone": "rushing_touchdown",
    "interception!": "interception",
    "field goal attempt is good": "field_goal",
    "what a sack!": "quarterback_sack",
    "pick six!": "pick_six",
    "fumble recovered": "fumble_recovery",
    "onside kick": "onside_kick",
    "penalty flag on the play": "penalty",
    "pass interference called": "pass_interference",
    "kickoff return for a touchdown": "kickoff_return_touchdown",
    
    # Basketball
    "he sinks the three-pointer": "three_pointer",
    "slam dunk!": "slam_dunk",
    "blocked shot": "block",
    "alley-oop": "alley_oop",
    "he makes the free throw": "free_throw",
    "fast break leads to a basket": "fast_break",
    "steal leads to a fast break": "steal",
    "rebound grabbed by": "rebound",
    "turnover committed by": "turnover",
    "foul called": "foul",
    
    # Baseball
    "he hits a home run": "home_run",
    "grand slam!": "grand_slam",
    "struck out swinging": "strikeout",
    "caught looking for strike three": "strikeout",
    "line drive to left field": "base_hit",
    "double play ends the inning": "double_play",
    "bunt laid down perfectly": "bunt",
    "fly ball to center field": "fly_ball",
    "wild pitch scores a run": "wild_pitch",
    "runners advance on a passed ball": "passed_ball",
    
    # Tennis
    "ace down the line": "ace",
    "match point": "match_point",
    "double fault": "double_fault",
    "break point opportunity": "break_point",
    "forehand winner": "forehand_winner",
    "backhand down the line": "backhand_winner",
    "unforced error": "unforced_error",
    "deuce on serve": "deuce",
    "game set and match": "match_end",
    
    # Cricket
    "what a six!": "six",
    "he hits it for four": "four",
    "bowled him out": "bowled",
    "caught at slip": "caught",
    "run out at the non-striker's end": "run_out",
    "wide ball called": "wide_ball",
    "no ball signaled": "no_ball",
    "century for the batsman": "century",
    "hat trick taken by the bowler": "hat_trick",
    
    # Hockey
    "goal scored!": "goal",
    "penalty shot awarded": "penalty_shot",
    "power play opportunity": "power_play",
    "hat trick for the forward": "hat_trick",
    "saved by the goalie": "save",
    "breakaway chance": "breakaway",
    "checking in the corner": "checking",
    "face-off in the offensive zone": "face_off",
    
    # Volleyball
    "spike for the point": "spike",
    "blocked at the net": "block",
    "perfect set": "set",
    "ace on the serve": "ace",
    "diving dig to save it": "dig",
    "kill wins the rally": "kill",
    "rally continues": "rally",
    
    # Golf
    "hole in one!": "hole_in_one",
    "birdie on the par four": "birdie",
    "eagle on the par five": "eagle",
    "bogey on the last hole": "bogey",
    "par for the course": "par",
    "drive down the fairway": "drive",
    "putts it in for par": "putt",
    
    # Swimming
    "freestyle stroke": "freestyle",
    "butterfly stroke": "butterfly",
    "backstroke in lane three": "backstroke",
    "breaststroke finish": "breaststroke",
    "relay exchange": "relay",
    "diving into the pool": "dive",
    "flip turn at the wall": "turn",
    "touches the wall to win": "finish",
}

